.gitignore
README.md
lib-chat/lib-chat.iml
lib-chat/pom.xml
lib-chat/src/main/java/top/xinsin/Start.java
lib-chat/src/main/resources/Application.yml
lib-fileTransfer/lib-fileTransfer.iml
lib-fileTransfer/pom.xml
lib-voice/lib-voice.iml
lib-voice/pom.xml
pom.xml

feat：add three modules,achieved separately chat,voice,fileTransfer

feat：add three modules,achieved separately chat,voice,fileTransfer

---

README.md

docs:Modify the readme.md file

docs:Modify the readme.md file

---

lib-chat/src/main/resources/Application.yml

fix: fix can't connect to server's bug

fix: fix can't connect to server's bug

---

lib-chat/src/main/java/top/xinsin/controller/Login.java
lib-chat/src/main/java/top/xinsin/controller/VerificationCode.java

fix: fix folderName

---

static/css/index.css
static/index.html
static/js/index.js

feat:add login

---

lib-chat/src/main/java/top/xinsin/controller/Login.java
lib-chat/src/main/java/top/xinsin/dao/UserMapper.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/resources/top/xinsin/dao/UserMapper.xml

feat: add change password function

feat: add change password function

---

lib-chat/src/main/java/top/xinsin/controller/LoginController.java
lib-chat/src/main/java/top/xinsin/controller/MessageController.java
lib-chat/src/main/java/top/xinsin/controller/VerificationCodeController.java
lib-chat/src/main/java/top/xinsin/dao/MessageMapper.java
lib-chat/src/main/java/top/xinsin/pojo/Message.java
lib-chat/src/main/java/top/xinsin/services/MessageService.java
lib-chat/src/main/resources/top/xinsin/dao/MessageMapper.xml
lib-chat/src/main/resources/top/xinsin/dao/UserMapper.xml

feat: add Message System

---

lib-chat/src/main/java/top/xinsin/Start.java
lib-chat/src/main/java/top/xinsin/Task/CheckTask.java
lib-chat/src/main/java/top/xinsin/controller/CheckController.java
lib-chat/src/main/java/top/xinsin/controller/MessageController.java
lib-chat/src/main/java/top/xinsin/dao/UserMapper.java
lib-chat/src/main/java/top/xinsin/pojo/User.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/resources/top/xinsin/dao/UserMapper.xml

feat: add checker

---

lib-chat/src/main/java/top/xinsin/configurations/Mvn.java
lib-chat/src/main/java/top/xinsin/configurations/Security.java
lib-chat/src/main/java/top/xinsin/controller/UserController.java
lib-chat/src/main/java/top/xinsin/controller/VerificationCodeController.java
lib-chat/src/main/resources/Application.yml
lib-chat/src/main/resources/static/login.html
pom.xml

feat: add Security System

---

lib-web/pom.xml
lib-web/static/css/index.css
lib-web/static/index.html

fix:更改前端页面

---

lib-chat/src/main/java/top/xinsin/controller/UserController.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/resources/Application.yml
lib-chat/src/test/java/cn/wzpmc/testMD5.java
pom.xml

fix:修复登录密码加密问题和登录返回false

---

witstalk/src/components/index.vue

fix: Fixed the bug that the page did not have rounded corners.

fix: Fixed the bug that the page did not have rounded corners.

---

lib-chat/src/main/java/top/xinsin/controller/UserController.java
lib-chat/src/main/java/top/xinsin/controller/VerificationCodeController.java
lib-chat/src/main/java/top/xinsin/services/UserService.java

fix:fix Known Bugs

---

http.md
lib-chat/src/main/java/top/xinsin/controller/UserController.java

docs:improved http.md

---

lib-chat/src/main/java/top/xinsin/Utils/ResponseData.java
lib-chat/src/main/java/top/xinsin/controller/CheckController.java
lib-chat/src/main/java/top/xinsin/controller/MessageController.java
lib-chat/src/main/java/top/xinsin/controller/UserController.java
lib-chat/src/main/java/top/xinsin/controller/VerificationCodeController.java
lib-chat/src/main/java/top/xinsin/enums/Auth.java
lib-chat/src/main/java/top/xinsin/enums/HttpStatus.java
lib-chat/src/main/java/top/xinsin/interceptor/AuthenticationInterceptor.java
lib-chat/src/main/java/top/xinsin/pojo/User.java
lib-chat/src/main/java/top/xinsin/services/MessageService.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/java/top/xinsin/services/VerificationCodeService.java
witstalk/src/pages/Chat/Chat.html
witstalk/src/pages/Chat/Chat.js
witstalk/src/pages/Chat/Chat.vue

refactor: refactor the back end code

refactor: refactor the back end code

---

witstalk/build/webpack.dev.conf.js
witstalk/config/index.js
witstalk/src/pages/Login/Login.vue

fix: fix can't login's bug

---

witstalk/src/pages/Login/Login.vue
witstalk/src/pages/Login/static/login.js

docs: Comment Added

---

lib-chat/src/main/java/top/xinsin/ChatStart.java
lib-chat/src/main/java/top/xinsin/config/InterceptorConfig.java
lib-chat/src/main/java/top/xinsin/controller/UserController.java
lib-fileTransfer/src/main/java/top/xinsin/FileTransferStart.java
lib-fileTransfer/src/main/java/top/xinsin/controller/FileUpLoadController.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileUpLoadService.java
lib-fileTransfer/src/main/resources/Application.yml
pom.xml
witstalk/src/pages/Login/Login.vue
witstalk/test/staticTest/upload.html

feat:add fileUpLoad

---

lib-fileTransfer/src/main/java/top/xinsin/dao/FileUpLoadDao.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileUpLoadService.java

fix:fix known bug

---

lib-chat/src/main/resources/top/xinsin/dao/MessageMapper.xml
lib-chat/src/main/resources/top/xinsin/dao/UserMapper.xml
lib-fileTransfer/src/main/java/top/xinsin/FileTransferStart.java
lib-fileTransfer/src/main/java/top/xinsin/controller/FileUpLoadController.java
lib-fileTransfer/src/main/java/top/xinsin/dao/FileUpLoadDao.java
lib-fileTransfer/src/main/java/top/xinsin/dao/FileUpLoadMapper.java
lib-fileTransfer/src/main/java/top/xinsin/pojo/FileObject.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileUpLoadService.java
lib-fileTransfer/src/main/resources/top/xinsin/dao/FileUpLoadMapper.xml

feat: add file upload function

feat: add file upload function

---

witstalk/src/pages/Chat/Chat.vue

fix : fixKnownBugs

---

lib-chat/src/main/java/top/xinsin/config/InterceptorConfig.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/resources/Application.yml
lib-fileTransfer/src/main/java/top/xinsin/service/FileUpLoadService.java
lib-fileTransfer/src/main/resources/Application.yml
lib-utils/src/main/java/top/xinsin/Utils/FileUtils.java
witstalk/src/pages/Login/Login.vue

feat: add FileUpload function

---

lib-chat/src/main/java/top/xinsin/controller/UserController.java
lib-chat/src/main/java/top/xinsin/dao/UserMapper.java
lib-chat/src/main/java/top/xinsin/pojo/User.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/resources/top/xinsin/dao/UserMapper.xml
lib-fileTransfer/src/main/java/top/xinsin/controller/FileDownloadController.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileDownloadService.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileUpLoadService.java

feat:addAvatar

---

lib-voice/src/test/java/top/xinsin/abstract1/Client.java
lib-voice/src/test/java/top/xinsin/abstract1/HuaWeiFactory.java
lib-voice/src/test/java/top/xinsin/abstract1/HuaWeiPhone.java
lib-voice/src/test/java/top/xinsin/abstract1/HuaWeiRouter.java
lib-voice/src/test/java/top/xinsin/abstract1/IProductFactory.java
lib-voice/src/test/java/top/xinsin/abstract1/IRouterProduct.java
lib-voice/src/test/java/top/xinsin/abstract1/IphoneProduct.java
lib-voice/src/test/java/top/xinsin/abstract1/XiaoMiFactory.java
lib-voice/src/test/java/top/xinsin/abstract1/XiaoMiPhone.java
lib-voice/src/test/java/top/xinsin/abstract1/XiaoMiRouter.java
lib-voice/src/test/java/top/xinsin/method/Car.java
lib-voice/src/test/java/top/xinsin/method/CarFactory.java
lib-voice/src/test/java/top/xinsin/method/Consumer.java
lib-voice/src/test/java/top/xinsin/method/Tesla.java
lib-voice/src/test/java/top/xinsin/method/TeslaFactory.java
lib-voice/src/test/java/top/xinsin/method/WuLing.java
lib-voice/src/test/java/top/xinsin/method/WuLingFactory.java
lib-voice/src/test/java/top/xinsin/simple/Car.java
lib-voice/src/test/java/top/xinsin/simple/CarFactory.java
lib-voice/src/test/java/top/xinsin/simple/Tesla.java
lib-voice/src/test/java/top/xinsin/simple/WuLing.java

test:add factory test

---

lib-chat/src/main/java/top/xinsin/controller/MessageController.java
lib-chat/src/main/java/top/xinsin/dao/MessageMapper.java
lib-chat/src/main/java/top/xinsin/pojo/Online.java
lib-chat/src/main/java/top/xinsin/pojo/User.java
lib-chat/src/main/java/top/xinsin/services/MessageService.java
lib-chat/src/main/java/top/xinsin/services/UserService.java
lib-chat/src/main/resources/top/xinsin/dao/MessageMapper.xml
lib-chat/src/main/resources/top/xinsin/dao/UserMapper.xml
witstalk/src/pages/Login/Login.vue
witstalk/src/pages/Login/static/login.js

feat:add getOnlineUser web interface;

feat:add getOnlineUser web interface;

---

web/src/components/mainpage.vue
web/src/pages/file/download.vue
web/src/pages/file/file.vue
web/src/pages/file/upload.vue
web/src/router/index.js

feat:add web file download.vue,upload.vue,file.vue

feat:add web file download.vue,upload.vue,file.vue

---

lib-chat/src/main/java/top/xinsin/controller/MessageController.java
lib-chat/src/main/java/top/xinsin/dao/MessageMapper.java
lib-chat/src/main/java/top/xinsin/services/MessageService.java
lib-chat/src/main/resources/top/xinsin/dao/MessageMapper.xml
lib-utils/src/main/java/top/xinsin/Utils/ResponseData.java
web/src/components/axios/request.js
web/src/pages/Chat/chat.vue

feat:add get count api

---

lib-chat/src/main/java/top/xinsin/interceptor/AuthenticationInterceptor.java
lib-fileTransfer/src/main/java/top/xinsin/config/GlobalWebMvcConfig.java
lib-fileTransfer/src/main/java/top/xinsin/config/InterceptorConfig.java
lib-fileTransfer/src/main/java/top/xinsin/controller/FileDownloadController.java
lib-fileTransfer/src/main/java/top/xinsin/dao/FileDownloadMapper.java
lib-fileTransfer/src/main/java/top/xinsin/interceptor/AuthenticationInterceptor.java
lib-fileTransfer/src/main/java/top/xinsin/pojo/FileObject.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileDownloadService.java
lib-fileTransfer/src/main/resources/top/xinsin/dao/FileDownloadMapper.xml
web/src/components/axios/axios_file.js
web/src/components/axios/request.js
web/src/components/login.vue
web/src/pages/file/download.vue
web/src/pages/file/file.vue

feat: add web download Features

feat: add web download Features

---

lib-chat/pom.xml
lib-voice/pom.xml
pom.xml
web/src/pages/file/upload.vue
web/src/router/index.js

refactor: update pom.xml

---

lib-chat/src/main/java/cn/wzpmc/ChatFrameHandler.java
lib-chat/src/main/java/cn/wzpmc/ChatHandler.java
lib-chat/src/main/java/cn/wzpmc/dao/ChatDao.java
lib-chat/src/main/resources/cn/wzpmc/dao/ChatDao.xml
lib-utils/src/main/java/top/xinsin/Utils/JWTTokenUtils.java

feat:adding chat function

---

lib-chat/src/main/java/cn/wzpmc/ChatFrameHandler.java
lib-chat/src/main/java/cn/wzpmc/ChatHandler.java
lib-user/src/main/java/top/xinsin/UserStart.java
lib-utils/pom.xml
web/src/components/login.vue
web/src/pages/Chat/chat.vue
web/src/pages/Chat/chat_bk.vue
web/src/pages/Chat/message.vue

fix: fixKnownBugs

---

lib-chat/src/main/java/cn/wzpmc/ChatFrameHandler.java
lib-chat/src/main/java/cn/wzpmc/dao/ChatDao.java
lib-chat/src/main/java/cn/wzpmc/pojo/HeadPortrait.java
lib-chat/src/main/java/cn/wzpmc/pojo/Message.java
lib-chat/src/main/resources/cn/wzpmc/dao/ChatDao.xml
web/src/components/mainpage.vue
web/src/pages/Chat/chat.vue
web/src/pages/Chat/message.vue

fix: fix known bugs

---

README.md
web/src/pages/VoiceChat/voicechat.vue

Fix: fixed syntax bug in Readme

Fix: fixed syntax bug in Readme

---

http.md
lib-user/src/main/java/top/xinsin/dao/UserMapper.java
lib-user/src/main/java/top/xinsin/services/UserService.java
lib-user/src/main/resources/top/xinsin/dao/UserMapper.xml

docs:complete http.md docs

---

lib-chat/src/main/java/cn/wzpmc/ChatFrameHandler.java
lib-chat/src/main/java/cn/wzpmc/dao/ChatDao.java
lib-chat/src/main/java/cn/wzpmc/pojo/Message.java
lib-chat/src/main/resources/cn/wzpmc/dao/ChatDao.xml
web/src/components/login.vue
web/src/pages/Chat/chat.vue
web/src/pages/Chat/message.vue

feat: adding recall function 

---

lib-chat/src/main/java/cn/wzpmc/ChatFrameHandler.java

perf: Remove redundant code

---

README.md
http.md
lib-fileTransfer/src/main/java/top/xinsin/controller/FileDownloadController.java
lib-user/src/test/java/cn/wzpmc/bk/Test02.java

docs:add Jetbrains Support Information

docs:add Jetbrains Support Information

---

lib-chat/src/main/resources/mybatis-config.xml
lib-fileTransfer/src/main/resources/Application.yml
lib-user/src/main/resources/Application.yml
lib-user/src/test/java/cn/wzpmc/bk/Test03.java
web/src/components/login.vue
web/src/components/mainpage.vue

fix:update database

---

.gitignore
lib-user/src/main/java/top/xinsin/services/UserService.java
lib-user/src/test/java/cn/wzpmc/bk/TestRegex.java
lib-user/src/test/java/cn/wzpmc/bk/testMD5.java
nginx-1.20.2/conf/fastcgi.conf
nginx-1.20.2/conf/fastcgi_params
nginx-1.20.2/conf/koi-utf
nginx-1.20.2/conf/koi-win
nginx-1.20.2/conf/mime.types
nginx-1.20.2/conf/scgi_params
nginx-1.20.2/conf/uwsgi_params
nginx-1.20.2/conf/win-utf
web/src/components/mainpage.vue
web/src/components/search.vue
web/src/mixin/mixin.js
web/src/pages/Chat/chat.vue
web/src/pages/Chat/message.vue

test:lib-user moudle add testRegex.java

test:lib-user moudle add testRegex.java

---

lib-chat/src/main/resources/mybatis-config.xml
lib-fileTransfer/src/main/resources/Application.yml
lib-user/src/main/resources/Application.yml
web/src/pages/VoiceChat/voicechat.vue

docs: change datasource

---

lib-fileTransfer/src/main/java/top/xinsin/controller/FileDownloadController.java
lib-fileTransfer/src/main/java/top/xinsin/controller/FileUpLoadController.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileDownloadService.java
lib-fileTransfer/src/main/java/top/xinsin/service/FileUpLoadService.java
lib-user/src/main/resources/application.yml
lib-utils/src/main/java/top/xinsin/enums/HttpCodes.java

refactor:refactor Unified Response Format and lib-fileTransfer

refactor:refactor Unified Response Format and lib-fileTransfer

---

lib-voice/src/main/java/cn/wzpmc/VoiceHandler.java
web/src/views/voice/index.vue

[fix: fix cannot connect to Voice Server bug](https://github.com/XinSin0/witsTalk/commit/07d1cd2d893a52124cc60efd0003bd6074d09c93)

fix: fix cannot connect to Voice Server bug

---

lib-chat/src/main/java/cn/wzpmc/Netty.java
lib-user/src/main/java/top/xinsin/controller/UserController.java
lib-utils/src/main/java/top/xinsin/utils/NettyUtils.java
lib-voice/src/main/java/cn/wzpmc/CommandHandler.java
web/components.d.ts
web/package-lock.json
web/src/components/User.vue
web/src/entities/Weather.ts
web/src/views/home/index.vue
web/src/views/voice/index.vue
web/yarn.lock

feat: adding group voice chat

---

web/src/components/User.vue
web/src/views/voice/index.vue

[docs: adding docs with User.vue](https://github.com/XinSin0/witsTalk/commit/07c8fb05e244740e2a31af0219213e98e557e00b)

docs: adding docs with User.vue

---

lib-utils/src/main/java/top/xinsin/utils/NettyUtils.java
lib-voice/src/main/java/cn/wzpmc/CommandHandler.java
web/src/components/User.vue
web/src/main.ts
web/src/views/home/index.vue
web/src/views/login/index.vue
web/src/views/voice/index.vue

fix: fix error when candidate is null

fix: fix error when candidate is null

---

lib-chat/src/main/java/cn/wzpmc/ChatFrameHandler.java
lib-chat/src/main/java/cn/wzpmc/ChatStart.java
lib-chat/src/main/java/cn/wzpmc/dao/ChatDao.java
lib-chat/src/main/java/cn/wzpmc/services/ChatCommandHandler.java
lib-chat/src/main/resources/cn/wzpmc/dao/ChatDao.xml
lib-utils/src/main/java/top/xinsin/interfaces/NettyCommandHandler.java
lib-utils/src/main/java/top/xinsin/utils/NettyUtils.java
lib-voice/src/main/java/cn/wzpmc/VoiceFrameHandler.java
lib-voice/src/main/java/cn/wzpmc/VoiceStart.java
lib-voice/src/main/java/cn/wzpmc/services/VoiceCommandHandler.java
web/components.d.ts
web/src/components/Message.vue
web/src/entities/MessageData.ts
web/src/views/chat/index.vue
web/src/views/home/index.vue
web/src/views/voice/index.vue

refactor: refactor the text chat page and update backend
feat: adding support with recall

refactor: refactor the text chat page and update backend
